# Site settings
title: Steppor
email: palipalo9@googlemail.com
description: "A Launchpad Step-Sequencer for Renoise"
keywords: "Renoise, Launchpad, Steppor, Step-Sequencer"
baseurl: "/stepp0r"
url: "http://mrvandalo.github.io"

actual_version: "Stepp0r-0.64.xrnx"

# Build settings
markdown: kramdown
permalink: pretty
limit_posts: 5
